"""Merlo semantic evolution sidecar and Closed Semantic Frontend labs."""

from .analyzer import ANALYZER_VERSION, AnalysisError, scan_python
from .changes import (
    ChangeDescriptor,
    changes_commute,
    changes_conflict,
    compose_changes,
)
from .core_semantics import (
    CORE_SCHEMA_ID,
    CORE_SCHEMA_SHA256,
    CORE_SCHEMA_VERSION,
    CapabilityViolation,
    CoreBindingError,
    CoreChange,
    CoreChangeResult,
    CoreError,
    CorePackage,
    CoreProgram,
    CoreReference,
    CoreSymbol,
    CoreWorld,
    apply_core_change,
    compile_core,
)
from .context import TaskCapsule, compile_context, source_read
from .evolution import (
    ChangeBlocked,
    apply_plan,
    plan_change_signature,
    plan_move,
    plan_rename,
    render_plan,
)
from .frontend_evaluator import (
    CapabilityValue,
    EvaluationError,
    EvaluationResult,
    ReferenceEvaluator,
)
from .frontend_semantics import (
    FrontendCheckResult,
    FrontendCompilation,
    FrontendCompileError,
    FrontendDiagnostic,
    TypedHIR,
    check_frontend,
    compile_frontend,
)
from .frontend_syntax import (
    FrontendSyntaxError,
    SourceCST,
    parse_source,
    parse_sources,
)
from .identity import IdentityResolver
from .model import (
    ChangePlan,
    ChangeSignature,
    EditCapability,
    Entity,
    Evidence,
    IdentityRelation,
    MoveSymbol,
    Obligation,
    ObligationGraph,
    ProgramIR,
    Reference,
    RenameSymbol,
    SemanticImpact,
)
from .protocol import MerloProtocol
from .world import SoftwareWorld, WorldError

__all__ = [
    "ANALYZER_VERSION",
    "AnalysisError",
    "ChangeBlocked",
    "ChangeDescriptor",
    "ChangePlan",
    "CapabilityViolation",
    "CORE_SCHEMA_ID",
    "CORE_SCHEMA_SHA256",
    "CORE_SCHEMA_VERSION",
    "CoreBindingError",
    "CoreChange",
    "CoreChangeResult",
    "CoreError",
    "CorePackage",
    "CoreProgram",
    "CoreReference",
    "CoreSymbol",
    "CoreWorld",
    "ChangeSignature",
    "EditCapability",
    "Entity",
    "Evidence",
    "CapabilityValue",
    "EvaluationError",
    "EvaluationResult",
    "FrontendCheckResult",
    "FrontendCompilation",
    "FrontendCompileError",
    "FrontendDiagnostic",
    "FrontendSyntaxError",
    "IdentityRelation",
    "IdentityResolver",
    "MerloProtocol",
    "MoveSymbol",
    "Obligation",
    "ObligationGraph",
    "ProgramIR",
    "Reference",
    "ReferenceEvaluator",
    "SourceCST",
    "TypedHIR",
    "RenameSymbol",
    "SemanticImpact",
    "SoftwareWorld",
    "TaskCapsule",
    "WorldError",
    "apply_plan",
    "apply_core_change",
    "changes_commute",
    "changes_conflict",
    "compile_context",
    "check_frontend",
    "compile_frontend",
    "compose_changes",
    "compile_core",
    "plan_change_signature",
    "plan_move",
    "plan_rename",
    "render_plan",
    "parse_source",
    "parse_sources",
    "scan_python",
    "source_read",
]
